-- BASE DE DATOS EN MYSQL

CREATE DATABASE RENTAS;

USE RENTAS;

CREATE TABLE ESTADO(
    IdEstado INT AUTO_INCREMENT,
    Estado VARCHAR(50) NOT NULL,
    CONSTRAINT PK_ESTADO PRIMARY KEY(IdEstado)
);

CREATE TABLE MUNICIPIO(
    IdMunicipio INT AUTO_INCREMENT,
    Municipio VARCHAR(50) NOT NULL,
    IdEstado INT NOT NULL,
    CONSTRAINT PK_MUNICIPIO PRIMARY KEY(IdMunicipio),
    CONSTRAINT FK_MUNICIPIOTOESTADO FOREIGN KEY(IdEstado) REFERENCES ESTADO(IdEstado)
);

CREATE TABLE CODIGOPOSTAL(
    IdCodigoPostal INT AUTO_INCREMENT,
    CodigoPostal VARCHAR(10) NOT NULL,
    IdMunicipio INT NOT NULL,
    CONSTRAINT PK_CODIGOPOSTAL PRIMARY KEY(IdCodigoPostal),
    CONSTRAINT FK_CODIGOPOSTALTOMUNICIPIO FOREIGN KEY(IdMunicipio) REFERENCES MUNICIPIO(IdMunicipio)
);

CREATE TABLE COLONIA(
    IdColonia INT AUTO_INCREMENT,
    Colonia VARCHAR(75) NOT NULL,
    IdCodigoPostal INT NOT NULL,
    CONSTRAINT PK_COLONIA PRIMARY KEY(IdColonia),
    CONSTRAINT FK_COLONIATOCODIGOPOSTAL FOREIGN KEY(IdCodigoPostal) REFERENCES CODIGOPOSTAL(IdCodigoPostal)
);

CREATE TABLE DIRECCION(
    IdDireccion INT AUTO_INCREMENT,
    IdCodigoPostal INT NOT NULL,
    IdColonia INT NOT NULL,
    Calle VARCHAR(75) NOT NULL,
    CONSTRAINT PK_DIRECCION PRIMARY KEY(IdDireccion),
    CONSTRAINT FK_DIRECCIONTOCODIGOPOSTAL FOREIGN KEY(IdCodigoPostal) REFERENCES CODIGOPOSTAL(IdCodigoPostal),
    CONSTRAINT FK_DIRECCIONTOCOLONIA FOREIGN KEY(IdColonia) REFERENCES COLONIA(IdColonia)
);


CREATE TABLE ROL(
  IdRol INT AUTO_INCREMENT,
  Rol VARCHAR(100),
  CONSTRAINT PK_ROL PRIMARY KEY(IdRol)
);

CREATE TABLE ESTATUS(
    IdEstatus INT AUTO_INCREMENT,
    Estatus VARCHAR(100),
    CONSTRAINT PK_ESTATUS PRIMARY KEY(IdEstatus)
);

CREATE TABLE PERSONA(
    IdPersona INT AUTO_INCREMENT,
    Nombre VARCHAR(300) NOT NULL,
    ApellidoPaterno VARCHAR(300) NOT NULL,
    ApellidoMaterno VARCHAR(300) NOT NULL,
    Telefono VARCHAR(15) NOT NULL,
    CONSTRAINT PK_PERSONA PRIMARY KEY(IdPersona)
);

CREATE TABLE EMPLEADO(
    IdEmpleado INT AUTO_INCREMENT,
    IdPersona INT NOT NULL,
    IdRol INT NOT NULL,
    IdEstatus INT NOT NULL,
    Fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_EMPLEADO PRIMARY KEY(IdEmpleado),
    CONSTRAINT FK_EMPLEADOTOPERSONA FOREIGN KEY(IdPersona) REFERENCES PERSONA(IdPersona) ON DELETE CASCADE,
    CONSTRAINT FK_EMPLEADOTOESTATUS FOREIGN KEY(IdEstatus) REFERENCES ESTATUS(IdEstatus) ON DELETE CASCADE,
    CONSTRAINT FK_EMPLEADOTOROL FOREIGN KEY(IdRol) REFERENCES ROL(IdRol) ON DELETE CASCADE
);

CREATE TABLE USUARIO(
    IdUsuario INT AUTO_INCREMENT,
    Contraseña VARCHAR(100) NOT NULL,
    IdEmpleado INT NOT NULL,
    CONSTRAINT PK_USUARIO PRIMARY KEY(IdUsuario),
    CONSTRAINT FK_USUARIOTOEMPLEADO FOREIGN KEY(IdEmpleado) REFERENCES EMPLEADO(IdEmpleado) ON DELETE CASCADE
);


ALTER TABLE USUARIO AUTO_INCREMENT = 1001;

CREATE TABLE PROPIEDAD(
    IdPropiedad INT AUTO_INCREMENT,
    Nombre VARCHAR(100) NOT NULL,
    Direccion INT NOT NULL,
    Tipo ENUM ('Casa', 'Edificio', 'Local') NOT NULL,
    Estatus ENUM ('Activo', 'Eliminado') DEFAULT 'Activo',
    CONSTRAINT PK_PROPIEDAD PRIMARY KEY(IdPropiedad),
    CONSTRAINT FK_PROPIEDADTODIRECCION FOREIGN KEY (Direccion) REFERENCES DIRECCION(IdDireccion)
);

CREATE TABLE UNIDAD(
    IdUnidad INT AUTO_INCREMENT,
    Nombre VARCHAR(100) NOT NULL,
    Propiedad INT NOT NULL,
    Estatus ENUM ('Activo', 'Eliminado') DEFAULT 'Activo',
    CONSTRAINT PK_UNIDAD PRIMARY KEY(IdUnidad),
    CONSTRAINT FK_UNIDADTOPROPIEDAD FOREIGN KEY (Propiedad) REFERENCES PROPIEDAD(IdPropiedad)
);

CREATE TABLE CONTRATO(
    IdContrato INT AUTO_INCREMENT,
    IdUnidad INT NULL,
    IdPropiedad INT NULL,
    IdPersona INT NOT NULL,
    MontoRenta DECIMAL(10,2),
    Deposito DECIMAL(10,2),
    FechaCreacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Plazo INT NOT NULL,
    Estado ENUM ('Activo', 'Finalizado', 'Cancelado') DEFAULT 'Activo',
    CONSTRAINT PK_CONTRATO PRIMARY KEY(IdContrato),
    CONSTRAINT FK_CONTRATOTOUNIDAD FOREIGN KEY(IdUnidad) REFERENCES UNIDAD(IdUnidad),
    CONSTRAINT FK_CONTRATOTOPROPIEDAD FOREIGN KEY(IdPropiedad) REFERENCES PROPIEDAD(IdPropiedad),
    CONSTRAINT FK_CONSTATOTOPERSONA FOREIGN KEY(IdPersona) REFERENCES PERSONA(IdPersona)
  --  CONSTRAINT CH_PROPIEDADOUNIDAD CHECK (IdUnidad IS NOT NULL AND IdPropiedad IS NULL OR IdPropiedad IS NOT NULL AND IdUnidad IS NULL)
);

CREATE TABLE CARGOFIJO(
    IdCargoFijo INT AUTO_INCREMENT,
    DiaCreacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    Descripcion VARCHAR(255) NOT NULL,
    Monto DECIMAL(10,2) NOT NULL,
    DiaCobro INT NOT NULL ,
    Plazo INT NOT NULL  DEFAULT -1,
    PlazoTranscurrido INT NOT NULL  DEFAULT 0,
    IdContrato INT NOT NULL,
    Estado ENUM('Completado', 'Activo', 'Perpetuo', 'Eliminado', 'Renta', 'Pausado', 'Cancelado') NOT NULL,
    CONSTRAINT PK_CARGOFIJO PRIMARY KEY(IdCargoFijo),
    CONSTRAINT CH_DIACOBRO CHECK ( DiaCobro >= 1 AND  DiaCobro <= 31 ),
    CONSTRAINT FK_CARGOFIJOTOCONTRATO FOREIGN KEY(IdContrato) REFERENCES CONTRATO(IdContrato)
);

CREATE TABLE CARGO(
    IdCargo INT AUTO_INCREMENT,
    IdContrato INT NOT NULL,
    TipoCargo ENUM ('Fijo', 'Variable', 'Extra'),
    Descripcion VARCHAR(255) NOT NULL,
    MontoTotal DECIMAL(10,2) NOT NULL,
    FechaInicio DATE NOT NULL,
    FechaVencimiento DATE NOT NULL,
    Estado ENUM ('Pendiente', 'Pagado', 'Parcial', 'Vencido', 'Programado', 'Eliminado', 'Cancelado') DEFAULT 'Pendiente',
    SaldoPendiente DECIMAL (10,2) NOT NULL ,
    CONSTRAINT PK_CARGO PRIMARY KEY(IdCargo),
    CONSTRAINT FK_CARGOTOCONTRATO FOREIGN KEY (IdContrato) REFERENCES CONTRATO(IdContrato)
);

CREATE TABLE ABONO(
    IdAbono INT AUTO_INCREMENT,
    IdCargo INT NOT NULL,
    Usuario INT NOT NULL,
    Fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    Monto DECIMAL(10,2) NOT NULL,
    CONSTRAINT PK_ABONO PRIMARY KEY(IdAbono),
    CONSTRAINT FK_ABONOTOEMPLEADO FOREIGN KEY(Usuario) REFERENCES USUARIO(IdUsuario),
    CONSTRAINT FK_ABONOTOCARGO FOREIGN KEY(IdCargo) REFERENCES CARGO(IdCargo)
);

DROP FUNCTION  IF EXISTS ObtenerDireccion;
CREATE FUNCTION ObtenerDireccion(ID INT)
RETURNS VARCHAR(100)
    DETERMINISTIC
    BEGIN
        DECLARE DIRECCION VARCHAR(100);
        SET DIRECCION = (SELECT CONCAT(E.Estado, ' ', M.Municipio, ' ', C2.Colonia, ' ', C.CodigoPostal) AS DIRECCION FROM ESTADO AS E INNER JOIN MUNICIPIO AS M ON E.IdEstado = M.IdEstado INNER JOIN CODIGOPOSTAL AS C ON M.IdMunicipio = C.IdMunicipio INNER JOIN COLONIA C2 on C.IdCodigoPostal = C2.IdCodigoPostal WHERE C.CodigoPostal = ID LIMIT 1);
        RETURN DIRECCION;
    end;

DROP FUNCTION IF EXISTS FN_OBTENERDIRECCION;
CREATE FUNCTION FN_OBTENERDIRECCION(IDDIR INT)
    RETURNS VARCHAR(100)
    DETERMINISTIC
    BEGIN
        DECLARE DIRECCION VARCHAR(100);
        DECLARE IDCOL INT;
        SET IDCOL = (SELECT IdColonia FROM DIRECCION WHERE IdDireccion = IDDIR LIMIT 1);
        SET DIRECCION = (SELECT CONCAT(D.Calle, ', ', C2.Colonia, ', ', M.Municipio, ', ', E.Estado) FROM DIRECCION AS D INNER JOIN CODIGOPOSTAL C on D.IdCodigoPostal = C.IdCodigoPostal INNER JOIN MUNICIPIO M on C.IdMunicipio = M.IdMunicipio INNER JOIN ESTADO E on M.IdEstado = E.IdEstado INNER JOIN COLONIA C2 on C.IdCodigoPostal = C2.IdCodigoPostal WHERE D.IdDireccion = IDDIR AND C2.IdColonia = IDCOL LIMIT 1);
        RETURN DIRECCION;
    end;

DROP FUNCTION IF EXISTS FN_OBTENER_Id_CodigoP;
CREATE FUNCTION FN_OBTENER_Id_CodigoP(COD INT)
    RETURNS VARCHAR(100)
    DETERMINISTIC
    BEGIN
        DECLARE IDCODVAR INT;
        SET IDCODVAR = (SELECT IdCodigoPostal FROM CODIGOPOSTAL AS C WHERE CodigoPostal = COD LIMIT 1);
        RETURN IDCODVAR;
    end;

-- STOCK PROCEDURE


DROP PROCEDURE IF EXISTS SP_OBTENERCOLONIAS;
CREATE PROCEDURE SP_OBTENERCOLONIAS(IN COD VARCHAR(10))
    BEGIN
        SELECT M.Municipio FROM CODIGOPOSTAL AS C INNER JOIN MUNICIPIO M on C.IdMunicipio = M.IdMunicipio WHERE C.CodigoPostal = COD LIMIT 1;
        SELECT C2.Colonia, C2.IdColonia AS VALUE FROM CODIGOPOSTAL AS C INNER JOIN COLONIA AS C2 ON C.IdCodigoPostal = C2.IdCodigoPostal WHERE C.CodigoPostal = COD;
        SELECT E.Estado FROM CODIGOPOSTAL AS C INNER JOIN MUNICIPIO AS M ON C.IdMunicipio = M.IdMunicipio INNER JOIN ESTADO AS E ON M.IdEstado = E.IdEstado WHERE C.CodigoPostal = COD LIMIT 1;
    end;

DROP PROCEDURE IF EXISTS SP_REGISTRARDIRECCION;
CREATE PROCEDURE SP_REGISTRARDIRECCION(IN COD VARCHAR(10), IN COL INT, IN CALLEIN VARCHAR(75), IN USERIN INT, OUT IDDIRVAR INT)
    BEGIN
        DECLARE IDCODVAR INT;
        SET IDCODVAR = (SELECT IdCodigoPostal FROM CODIGOPOSTAL AS C WHERE CodigoPostal = COD LIMIT 1);
        INSERT INTO DIRECCION (IdCodigoPostal, IdColonia, Calle) VALUES (IDCODVAR, COL, CALLEIN);
        SET IDDIRVAR = (SELECT LAST_INSERT_ID());
    end;

DROP PROCEDURE IF EXISTS SP_REGISTRARPERSONA;
CREATE PROCEDURE SP_REGISTRARPERSONA(IN NOMBREIN VARCHAR(300), IN APELLIDOPAT VARCHAR(300), IN APELLIDOMAT VARCHAR(300), IN TELEFONOIN VARCHAR(300), IN USERIN INT, OUT LASTIDPER INT)
    BEGIN
        INSERT INTO PERSONA (Nombre, ApellidoPaterno, ApellidoMaterno, Telefono) VALUES (NOMBREIN, APELLIDOPAT, APELLIDOMAT, TELEFONOIN);
        SET LASTIDPER = (SELECT LAST_INSERT_ID());
    end;

DROP PROCEDURE IF EXISTS SP_REGISTRAREMPLEADO;
CREATE PROCEDURE SP_REGISTRAREMPLEADO(IN CONTRASEÑAIN VARCHAR(100), IN NOMBREIN VARCHAR(300), IN APELLIDOPAT VARCHAR(300), IN APELLIDOMAT VARCHAR(300), IN TELEFONOIN VARCHAR(300), IN IDROLIN INT, IN IDEST INT, IN USERIN INT)
    BEGIN
        DECLARE  IdEMPVAR INT;
        DECLARE IDPERVAR INT;

        CALL SP_REGISTRARPERSONA(NOMBREIN, APELLIDOPAT, APELLIDOMAT, TELEFONOIN, USERIN, IDPERVAR);
        INSERT INTO EMPLEADO (IdPersona, IdRol, IdEstatus) VALUES (IDPERVAR, IDROLIN, IDEST);
        SET IdEMPVAR = (SELECT LAST_INSERT_ID());
        INSERT INTO USUARIO (Contraseña, IdEmpleado) VALUES (CONTRASEÑAIN, IdEMPVAR);
        SET IdEMPVAR = (SELECT LAST_INSERT_ID());
    end;

-- LOGIN
DROP PROCEDURE IF EXISTS LOGIN;
CREATE PROCEDURE LOGIN(IN ID INT, IN PASSWORD VARCHAR(50))
BEGIN
    DECLARE USERREGISTER INT;
    DECLARE PASST INT;
    DECLARE USERSTATUS INT;


    SET USERREGISTER = (SELECT IdUsuario FROM USUARIO WHERE IdUsuario = ID);
    IF USERREGISTER IS NULL THEN
        SELECT 0 AS RES; -- EL USUARIO NO EXISTE
    ELSE
        SET PASST = (SELECT IdUsuario FROM USUARIO WHERE IdUsuario = ID AND Contraseña = PASSWORD);
        IF PASST IS NULL THEN
            SELECT 1 AS RES; -- CONTRASEÑA INCORRECTA
        ELSE
            SET USERSTATUS = (SELECT IdEstatus FROM EMPLEADO AS E INNER JOIN USUARIO AS U ON E.IdEmpleado = U.IdEmpleado WHERE U.IdUsuario = ID );
            IF USERSTATUS != 1 THEN
                SELECT 2 AS RES; -- EL ESTATUS NO ESTA ACTIVO
            ELSE
                SELECT U.IdUsuario, E.IdRol, E.IdEstatus, P.Nombre, P.ApellidoPaterno AS Apellido FROM USUARIO AS U INNER JOIN EMPLEADO AS E ON U.IdEmpleado = E.IdEmpleado INNER JOIN PERSONA AS P ON E.IdPersona = P.IdPersona WHERE IdUsuario = ID AND Contraseña = PASSWORD;
            end if;
        end if;
    end if;
END;

DROP PROCEDURE IF EXISTS LOGIN_ESTATUS; --   PARA QUE FUNCIONE CON EL HASH DE CONTRASEÑAS
CREATE PROCEDURE LOGIN_ESTATUS(IN ID INT, IN OPT INT)
BEGIN
    DECLARE USERREGISTER INT;
    DECLARE USERSTATUS INT;

    IF OPT = 1 THEN
        SELECT Contraseña FROM USUARIO WHERE IdUsuario = ID;
    ELSE
        SET USERREGISTER = (SELECT IdUsuario FROM USUARIO WHERE IdUsuario = ID);
        IF USERREGISTER IS NULL THEN
            SELECT 0 AS RES; -- EL USUARIO NO EXISTE
        ELSE
            SET USERSTATUS = (SELECT IdEstatus FROM EMPLEADO AS E INNER JOIN USUARIO AS U ON E.IdEmpleado = U.IdEmpleado WHERE U.IdUsuario = ID );
            IF USERSTATUS != 1 THEN
                SELECT 1 AS RES; -- EL ESTATUS NO ESTA ACTIVO
            ELSE
                SELECT 2 AS RES; -- EL USUARIO EXISTE Y ESTA ACTIVO
            end if;
        end if;
    end if;
END;

DROP PROCEDURE IF EXISTS SP_GETUSERINFO;
CREATE PROCEDURE SP_GETUSERINFO(IN ID INT)
    BEGIN
        SELECT U.IdUsuario, E.IdRol, E.IdEstatus, P.Nombre, P.ApellidoPaterno AS Apellido FROM USUARIO AS U INNER JOIN EMPLEADO AS E ON U.IdEmpleado = E.IdEmpleado INNER JOIN PERSONA AS P ON E.IdPersona = P.IdPersona WHERE IdUsuario = ID;
    end;

-- Administrador/Empleados

DROP PROCEDURE IF EXISTS SP_GETEMPLEADOS;
CREATE PROCEDURE SP_GETEMPLEADOS(IN IDEMP INT)
    BEGIN
        SELECT U.IdUsuario AS ID, E.IdEmpleado AS IdEmp, CONCAT(P.Nombre, ' ', P.ApellidoPaterno, ' ', P.ApellidoMaterno) AS Nombre, P.Telefono, R.Rol, E2.Estatus FROM EMPLEADO AS E INNER JOIN PERSONA P on E.IdPersona = P.IdPersona INNER JOIN ROL R on E.IdRol = R.IdRol INNER JOIN ESTATUS E2 on E.IdEstatus = E2.IdEstatus INNER JOIN USUARIO U on E.IdEmpleado = U.IdEmpleado WHERE E2.IdEstatus != 4 AND U.IdUsuario != IDEMP ORDER BY U.IdUsuario;
    end;

DROP PROCEDURE IF EXISTS SP_DELETEEMPLEADO;
CREATE PROCEDURE SP_DELETEEMPLEADO(IN ID INT, IN USERID INT)
    BEGIN
        DECLARE NOMBREVAR VARCHAR(100);
        SET NOMBREVAR = (SELECT CONCAT(P.Nombre, ' ', P.ApellidoPaterno) FROM USUARIO AS U INNER JOIN  EMPLEADO E2 on U.IdEmpleado = E2.IdEmpleado INNER JOIN PERSONA P on E2.IdPersona = P.IdPersona WHERE E2.IdEmpleado = ID);
        UPDATE EMPLEADO SET IdEstatus = 4 WHERE IdEmpleado = ID;
    end;

DROP PROCEDURE IF EXISTS SP_GETEMPLEADO;
CREATE PROCEDURE SP_GETEMPLEADO(IN IDIN INT)
    BEGIN
        SELECT P.Nombre, P.ApellidoPaterno, P.ApellidoMaterno, P.Telefono, E.IdRol AS 'Rol', E.IdEstatus AS 'Estatus' FROM PERSONA AS P INNER JOIN EMPLEADO AS E ON P.IdPersona = E.IdPersona WHERE E.IdEmpleado = IDIN;
    end;

DROP PROCEDURE IF EXISTS SP_UPDATEEMPLEADO;
CREATE PROCEDURE SP_UPDATEEMPLEADO(IN EMPLEADOIN INT, IN NOMBREIN VARCHAR(50), IN APELLIDOPAT VARCHAR(50), IN APELLIDOMAT VARCHAR(50), IN TELEFONOIN VARCHAR(10), IN ROLIN INT, IN ESTATUSIN INT)
    BEGIN
        DECLARE IDPERSONAVAR INT;
        SET IDPERSONAVAR = (SELECT P.IdPersona FROM PERSONA AS P INNER JOIN EMPLEADO E on P.IdPersona = E.IdPersona WHERE E.IdEmpleado = EMPLEADOIN);

        IF IDPERSONAVAR IS NULL THEN
            SELECT 2 AS RES;
        ELSE
            SELECT 1 AS RES;
        end if;

        UPDATE PERSONA SET Nombre = NOMBREIN, ApellidoPaterno = APELLIDOPAT, ApellidoMaterno = APELLIDOMAT, Telefono = TELEFONOIN WHERE IdPersona = IDPERSONAVAR;
        UPDATE EMPLEADO SET IdEstatus = ESTATUSIN, IdRol = ROLIN WHERE IdEmpleado = EMPLEADOIN;
    end;

DROP PROCEDURE IF EXISTS SP_FINDEMPLEADO;
CREATE PROCEDURE SP_FINDEMPLEADO(IN NOMBREIN VARCHAR(100))
    BEGIN
        SELECT U.IdUsuario AS ID, E.IdEmpleado AS IdEmp, CONCAT(P.Nombre, ' ', P.ApellidoPaterno, ' ', P.ApellidoMaterno) AS Nombre, P.Telefono, R.Rol, E2.Estatus FROM EMPLEADO AS E INNER JOIN PERSONA P on E.IdPersona = P.IdPersona INNER JOIN ROL R on E.IdRol = R.IdRol INNER JOIN ESTATUS E2 on E.IdEstatus = E2.IdEstatus INNER JOIN USUARIO U on E.IdEmpleado = U.IdEmpleado WHERE E2.IdEstatus != 4 AND CONCAT(P.Nombre, ' ', P.ApellidoPaterno, ' ', P.ApellidoMaterno) LIKE CONCAT(NOMBREIN, '%') ORDER BY U.IdUsuario;
    end;

-- Administrador/PROPIEDADES

DROP PROCEDURE IF EXISTS SP_ADDPROPIEDAD;
CREATE PROCEDURE SP_ADDPROPIEDAD(IN NOMBREIN VARCHAR(100), IN TIPOIN VARCHAR(20),IN COD VARCHAR(10), IN COL INT, IN CALLEIN VARCHAR(75))
    BEGIN
        DECLARE IDDIROUT INT;
        -- REGISTRAR DIRECCION
        CALL SP_REGISTRARDIRECCION(COD, COL, CALLEIN,1, IDDIROUT);

        -- REGISTRAR PROPIEDAD
        INSERT INTO PROPIEDAD(NOMBRE, DIRECCION, Tipo) VALUES (NOMBREIN, IDDIROUT, TIPOIN);
    end;

DROP PROCEDURE IF EXISTS SP_ADDUNIDAD;
CREATE PROCEDURE SP_ADDUNIDAD(IN NOMBREIN VARCHAR(100), IN PROPIEDADIN INT)
    BEGIN
        INSERT INTO UNIDAD (Nombre, Propiedad) VALUES (NOMBREIN, PROPIEDADIN);
    end;

DROP FUNCTION  IF EXISTS FN_GETSUMUNIDADES;
CREATE FUNCTION FN_GETSUMUNIDADES(ID INT)
RETURNS INT
    DETERMINISTIC
    BEGIN
        DECLARE SUMUNIDADES INT;
        SET SUMUNIDADES = (SELECT COUNT(U.IdUnidad) FROM UNIDAD AS U WHERE U.Propiedad = ID AND U.Estatus = 'Activo');
        RETURN SUMUNIDADES;
    end;

DROP FUNCTION IF EXISTS FN_GETUNIDADESOCUPADAS;
CREATE FUNCTION FN_GETUNIDADESOCUPADAS(IDPROP INT)
    RETURNS INT
    DETERMINISTIC
    BEGIN
        DECLARE SUMUNIDADES, UNIDADESOCUPADAS INT;
        DECLARE TIPOVAR VARCHAR(20);
        SET TIPOVAR = (SELECT P.TIPO FROM PROPIEDAD AS P WHERE P.IdPropiedad = IDPROP);

        SET SUMUNIDADES = (SELECT FN_GETSUMUNIDADES(IDPROP));

        IF TIPOVAR != 'Edificio' THEN
            SET UNIDADESOCUPADAS = (SELECT COUNT(C.IdContrato) FROM CONTRATO AS C WHERE C.IdPropiedad = IDPROP AND C.Estado = 'Activo') ;
            ELSE
            SET UNIDADESOCUPADAS = (SELECT COUNT(C.IdContrato) FROM CONTRATO AS C INNER JOIN UNIDAD U on C.IdUnidad = U.IdUnidad AND C.Estado = 'Activo' WHERE U.Propiedad = IDPROP AND U.Estatus = 'Activo');
        end if;
        RETURN UNIDADESOCUPADAS;
    end;

DROP FUNCTION IF EXISTS FN_GETNOMBREBYID;
CREATE FUNCTION FN_GETNOMBREBYID(IDPER INT)
    RETURNS VARCHAR(40)
    DETERMINISTIC
    BEGIN
        DECLARE NOMBREVAR VARCHAR(40);

        SET NOMBREVAR = (SELECT CONCAT(P.Nombre, ' ', P.ApellidoPaterno) FROM PERSONA AS P WHERE P.IdPersona = IDPER);
        RETURN NOMBREVAR;
    end;

DROP FUNCTION IF EXISTS FN_GETPRECIORENTA;
CREATE FUNCTION FN_GETPRECIORENTA(IDPROP INT, UNIDADBOOL BOOLEAN)
    RETURNS DECIMAL(10,2)
    DETERMINISTIC
    BEGIN
        DECLARE RENTAVAR DECIMAL(10,2);

        -- SABER SI SE TRATA DE UNA PROPIEDAD O UNA UNIDAD
        IF UNIDADBOOL THEN
            SET RENTAVAR = (SELECT C.MontoRenta FROM CONTRATO AS C WHERE C.IdUnidad = IDPROP AND C.Estado = 'Activo' LIMIT 1);
            ELSE
            SET RENTAVAR = (SELECT C.MontoRenta FROM CONTRATO AS C WHERE C.IdPropiedad = IDPROP AND C.Estado = 'Activo' LIMIT 1);
        end if;

        RETURN RENTAVAR;

    end;

DROP FUNCTION IF EXISTS FN_GETCONTRATOPROPIEDAD;
CREATE FUNCTION FN_GETCONTRATOPROPIEDAD(IDPROP INT)
    RETURNS INT
    DETERMINISTIC
    BEGIN
        DECLARE IDCONTRATOVAR INT;

        SET IDCONTRATOVAR = (SELECT C.IdContrato FROM CONTRATO AS C WHERE C.IdPropiedad = IDPROP AND C.IdUnidad IS NULL AND C.Estado = 'Activo' LIMIT 1);

        RETURN IDCONTRATOVAR;

    end;

DROP FUNCTION IF EXISTS FN_GETPAGOSVENCIDOSPROPIEDADES;
CREATE FUNCTION FN_GETPAGOSVENCIDOSPROPIEDADES(IDPROP INT)
    RETURNS INT
    DETERMINISTIC
    BEGIN
        DECLARE SUMUPAGOS INT;

        SET SUMUPAGOS = (SELECT COUNT(C.IdCargo) FROM CARGO AS C INNER JOIN CONTRATO C2 on C.IdContrato = C2.IdContrato WHERE C2.IdPropiedad = IDPROP AND C2.IdUnidad IS NULL AND C.Estado = 'Vencido');

        RETURN SUMUPAGOS;
    end;

DROP PROCEDURE IF EXISTS SP_GETPROPIEDADES;
CREATE PROCEDURE SP_GETPROPIEDADES()
    BEGIN
        SELECT P.IdPropiedad, P.Nombre AS NombrePropiedad, (SELECT FN_GETSUMUNIDADES(P.IdPropiedad)) AS NumUnidades, (SELECT FN_OBTENERDIRECCION(P.Direccion)) AS Direccion, P.Tipo, (SELECT FN_GETUNIDADESOCUPADAS(P.IdPropiedad)) AS Ocupados, (SELECT FN_GETNOMBREBYID(C.IdPersona)) AS Inquilino, (SELECT FN_GETPRECIORENTA(P.IdPropiedad, FALSE)) AS Renta, DATE_FORMAT(C.FechaCreacion, '%d/%m/%Y') AS FechaInicio, (SELECT FN_GETCONTRATOPROPIEDAD(P.IdPropiedad)) AS Contrato, (SELECT FN_GETPAGOSVENCIDOSPROPIEDADES(P.IdPropiedad)) AS PagosVencidos FROM PROPIEDAD AS P LEFT JOIN CONTRATO C on P.IdPropiedad = C.IdPropiedad AND C.Estado = 'Activo' WHERE P.Estatus = 'Activo';
    end;

DROP PROCEDURE IF EXISTS SP_GETPROPIEDADBYID;
CREATE PROCEDURE SP_GETPROPIEDADBYID(IN IDIN INT)
    BEGIN
        SELECT P.Nombre, P.Tipo, C.CodigoPostal AS Codigo, D.IdColonia AS Colonia, C2.Colonia AS NombreColonia, D.Calle FROM PROPIEDAD AS P INNER JOIN DIRECCION D on P.Direccion = D.IdDireccion INNER JOIN CODIGOPOSTAL C on D.IdCodigoPostal = C.IdCodigoPostal INNER JOIN COLONIA C2 on C.IdCodigoPostal = C2.IdCodigoPostal WHERE P.IdPropiedad = IDIN AND P.Estatus = 'Activo';
    end;

DROP PROCEDURE IF EXISTS SP_EDITPROPIEDAD;
CREATE PROCEDURE SP_EDITPROPIEDAD(IN IDIN INT, IN NOMBREIN VARCHAR(100), IN TIPOIN VARCHAR(20),IN COD VARCHAR(10), IN COL INT, IN CALLEIN VARCHAR(75))
    BEGIN
        DECLARE IDDIR, NUMUNIDADES INT;
        DECLARE TIPOVAR VARCHAR(50);

        SET TIPOVAR = (SELECT P.Tipo FROM PROPIEDAD AS P WHERE P.IdPropiedad = IDIN);

        IF TIPOVAR = 'Edificio' AND TIPOVAR != TIPOIN THEN

            SET NUMUNIDADES = (SELECT FN_GETSUMUNIDADES(IDIN));

            IF NUMUNIDADES > 0 THEN
                SELECT 1 AS RES;
                SET TIPOIN = TIPOVAR;
            end if;

        ELSE
            SELECT 0 AS RES;
        end if;

        SET IDDIR = (SELECT P.Direccion FROM PROPIEDAD AS P WHERE P.IdPropiedad = IDIN);
        UPDATE PROPIEDAD SET Nombre = NOMBREIN, Tipo = TIPOIN WHERE IdPropiedad = IDIN;
        UPDATE DIRECCION SET IdCodigoPostal = (SELECT FN_OBTENER_Id_CodigoP(COD)), IdColonia = COL, Calle = CALLEIN WHERE IdDireccion = IDDIR;

    end;

DROP PROCEDURE IF EXISTS SP_DELETEPROPIEDAD;
CREATE PROCEDURE SP_DELETEPROPIEDAD(IN IDPROP INT)
    BEGIN

        UPDATE PROPIEDAD SET Estatus = 'Eliminado' WHERE IdPropiedad = IDPROP;
        UPDATE UNIDAD AS U SET Estatus = 'Eliminado' WHERE U.Propiedad = IDPROP;
        UPDATE CONTRATO AS C SET Estado = 'Cancelado' WHERE C.IdPropiedad = IDPROP;
        UPDATE CONTRATO AS C INNER JOIN UNIDAD AS U ON C.IdUnidad = U.IdUnidad SET C.Estado = 'Cancelado' WHERE U.Propiedad = IDPROP;

        UPDATE CARGOFIJO AS C INNER JOIN CONTRATO AS CO ON C.IdContrato = CO.IdContrato INNER JOIN PROPIEDAD AS P ON CO.IdPropiedad = P.IdPropiedad SET C.Estado = 'Eliminado' WHERE P.IdPropiedad = IDPROP;

        UPDATE CARGO AS C INNER JOIN CONTRATO AS CO ON C.IdContrato = CO.IdContrato INNER JOIN PROPIEDAD AS P ON CO.IdPropiedad = P.IdPropiedad SET C.Estado = 'Eliminado' WHERE P.IdPropiedad = IDPROP;

    end;

-- Administrador/PROPIEDADES

DROP FUNCTION IF EXISTS FN_GETPAGOSVENCIDOSUNIDADES;
CREATE FUNCTION FN_GETPAGOSVENCIDOSUNIDADES(IDUNI INT)
    RETURNS INT
    DETERMINISTIC
    BEGIN
        DECLARE SUMUPAGOS INT;

        SET SUMUPAGOS = (SELECT COUNT(C.IdCargo) FROM CARGO AS C INNER JOIN CONTRATO C2 on C.IdContrato = C2.IdContrato WHERE C2.IdUnidad = IDUNI AND C.Estado = 'Vencido');

        RETURN SUMUPAGOS;
    end;

DROP PROCEDURE IF EXISTS SP_GETUNIDADES;
CREATE PROCEDURE SP_GETUNIDADES(IN IDPROPIN INT)
    BEGIN
        SELECT P.Nombre AS NombrePropiedad FROM PROPIEDAD AS P WHERE IdPropiedad = IDPROPIN;
        SELECT U.IdUnidad, U.Nombre AS NombreUnidad, (SELECT FN_GETNOMBREBYID(C.IdPersona)) AS Inquilino, (SELECT FN_GETPRECIORENTA(U.IdUnidad, TRUE)) AS Renta, DATE_FORMAT(C.FechaCreacion, '%d/%m/%Y') AS FechaInicio, (SELECT FN_GETPAGOSVENCIDOSUNIDADES(U.IdUnidad)) AS PagosVencidos, C.IdContrato AS Contrato FROM UNIDAD AS U LEFT JOIN CONTRATO AS C ON U.IdUnidad = C.IdUnidad WHERE U.Propiedad = IDPROPIN AND U.Estatus = 'Activo' AND (C.Estado = 'Activo' OR C.Estado IS NULL);
    end;

DROP PROCEDURE IF EXISTS SP_DELETEUNIDAD;
CREATE PROCEDURE SP_DELETEUNIDAD(IN IDUNI INT)
    BEGIN
        UPDATE UNIDAD SET Estatus = 'Eliminado' WHERE IdUnidad = IDUNI;
        UPDATE CONTRATO AS C SET Estado = 'Cancelado' WHERE C.IdUnidad = IDUNI;

        UPDATE CARGOFIJO AS C INNER JOIN CONTRATO AS CO ON C.IdContrato = CO.IdContrato INNER JOIN UNIDAD AS P ON CO.IdUnidad = P.IdUnidad SET C.Estado = 'Eliminado' WHERE P.IdUnidad = IDUNI;

        UPDATE CARGO AS C INNER JOIN CONTRATO AS CO ON C.IdContrato = CO.IdContrato INNER JOIN UNIDAD AS P ON CO.IdUnidad = P.IdUnidad SET C.Estado = 'Eliminado' WHERE P.IdUnidad = IDUNI;

    end;

DROP PROCEDURE IF EXISTS SP_GETUNIDADADBYID;
CREATE PROCEDURE SP_GETUNIDADADBYID(IN IDIN INT)
    BEGIN
        SELECT U.Nombre FROM UNIDAD AS U WHERE U.IdUnidad = IDIN AND U.Estatus = 'Activo';
    end;

DROP PROCEDURE IF EXISTS SP_UPDATEUNIDAD;
CREATE PROCEDURE SP_UPDATEUNIDAD(IN IDIN INT, IN NOMBREIN VARCHAR(50))
    BEGIN
        UPDATE UNIDAD SET Nombre = NOMBREIN WHERE IdUnidad = IDIN;
    end;

-- Administrador/INQUILINOS

DROP PROCEDURE IF EXISTS SP_REGISTRARCONTRATO;
CREATE PROCEDURE SP_REGISTRARCONTRATO(IN NOMBREIN VARCHAR(300), IN APELLIDOPAT VARCHAR(300), IN APELLIDOMAT VARCHAR(300), IN TELEFONOIN VARCHAR(300), IN INMUEBLE INT, IN PROPBOOL INT, IN MONTOIN DECIMAL(10,2), IN DEPOIN DECIMAL(10,2), IN PLAZOIN INT, IN DIACOBROIN INT)
    BEGIN

        DECLARE INTPROP, INTUNIDAD, IDPERVAR, IDCONTRATOVAR INT;
        DECLARE NOMBREINMUEBLE, FECHADESC, FECHALIMITEVAR, FECHAINICIOVAR VARCHAR(100);

        DECLARE EXIT HANDLER FOR SQLEXCEPTION
            BEGIN
                -- SI OCURRE UN ERROR, DESHACER LOS CAMBIOS
                ROLLBACK;
            end;

        START TRANSACTION;

        IF PROPBOOL = 1 THEN
            SET INTPROP = INMUEBLE;
            SET INTUNIDAD = NULL;
            SET NOMBREINMUEBLE = (SELECT P.Nombre FROM PROPIEDAD AS P WHERE P.IdPropiedad = INMUEBLE);
        ELSE
            SET INTPROP = (SELECT U.IdUnidad FROM UNIDAD AS U WHERE U.IdUnidad = INMUEBLE);
            SET INTUNIDAD = INMUEBLE;
            SET NOMBREINMUEBLE = (SELECT CONCAT(P2.Nombre, ' ', U.Nombre) FROM UNIDAD AS U INNER JOIN PROPIEDAD P2 on U.Propiedad = P2.IdPropiedad WHERE U.IdUnidad = INMUEBLE);
        end if;

        CALL SP_REGISTRARPERSONA(NOMBREIN, APELLIDOPAT, APELLIDOMAT, TELEFONOIN, 1, IDPERVAR);

        INSERT INTO CONTRATO (IdUnidad, IdPropiedad, IdPersona, MontoRenta, Deposito, Plazo) VALUES (INTUNIDAD, INTPROP, IDPERVAR, MONTOIN, DEPOIN, PLAZOIN);

        SET IDCONTRATOVAR = (SELECT LAST_INSERT_ID());

        INSERT INTO CARGOFIJO (Descripcion, Monto, DiaCobro, IdContrato, Estado) VALUES (CONCAT('Renta ', NOMBREINMUEBLE),MONTOIN,DIACOBROIN, IDCONTRATOVAR, 'Renta');

        SET FECHAINICIOVAR = (DATE_ADD(DATE_FORMAT(CURDATE(), CONCAT('%Y-%m-', LPAD(DIACOBROIN, 2, '0'))), INTERVAL 1 MONTH));
        SET FECHADESC = (DATE_FORMAT(FECHAINICIOVAR, '%d/%m/%Y'));
        SET FECHALIMITEVAR = (DATE_ADD(FECHAINICIOVAR, INTERVAL 2 WEEK));

        -- INSERT INTO CARGO (IdContrato, TipoCargo, Descripcion, MontoTotal, FechaInicio, FechaVencimiento, Estado, SaldoPendiente) VALUES (IDCONTRATOVAR, 'Fijo', (CONCAT('Renta ', FECHADESC, ' ', NOMBREINMUEBLE)), MONTOIN, FECHAINICIOVAR, FECHALIMITEVAR, 'Programado', MONTOIN);

        COMMIT;
    end;

-- ADMINISTRADOR/CRON

DROP PROCEDURE IF EXISTS SP_ACTIVARPAGOS;
CREATE PROCEDURE SP_ACTIVARPAGOS()
    BEGIN
        UPDATE CARGO SET Estado = 'Pendiente' WHERE FechaInicio = CURDATE() AND Estado = 'Programado' ;

        UPDATE CARGO SET Estado = 'Vencido' WHERE FechaVencimiento < CURDATE() AND (Estado = 'Pendiente' OR Estado = 'Parcial');

        INSERT INTO CARGO (IdContrato, TipoCargo, Descripcion, MontoTotal, FechaInicio, FechaVencimiento, SaldoPendiente) SELECT C.IdContrato, 'Fijo', (CONCAT(C.Descripcion, ' ', DATE_FORMAT(curdate(), '%d/%m/%Y'))), C.Monto, CURDATE(), (DATE_ADD(CURDATE(), INTERVAL 2 WEEK)), C.Monto FROM CARGOFIJO AS C INNER JOIN CONTRATO AS CO ON C.IdContrato = CO.IdContrato WHERE C.DiaCobro = DAY(CURDATE()) AND ((C.Estado = 'Renta' AND DATEDIFF(CURDATE(), CO.FechaCreacion) >= 30) OR C.Estado = 'Activo' OR C.Estado = 'Perpetuo');

        -- INSERT INTO CARGO (IdContrato, TipoCargo, Descripcion, MontoTotal, FechaInicio, FechaVencimiento, SaldoPendiente) SELECT C.IdContrato, 'Fijo', (CONCAT(C.Descripcion, ' ', DATE_FORMAT(curdate(), '%d/%m/%Y'), ' ', PR.Nombre)), C.Monto, CURDATE(), (DATE_ADD(CURDATE(), INTERVAL 2 WEEK)), C.Monto FROM CARGOFIJO AS C INNER JOIN CONTRATO AS CO ON C.IdContrato = CO.IdContrato INNER JOIN PROPIEDAD AS PR ON CO.IdPropiedad = PR.IdPropiedad WHERE C.DiaCobro = DAY(CURDATE()) AND CO.IdUnidad IS NULL AND (C.Estado = 'Perpetuo' OR C.Estado = 'Activo') AND ((C.Estado = 'Perpetuo' AND DATEDIFF(CURDATE(), CO.FechaCreacion) >= 30) OR C.Estado = 'Activo');

        UPDATE CARGOFIJO AS C INNER JOIN CONTRATO AS CO ON C.IdContrato = CO.IdContrato SET C.PlazoTranscurrido = (C.PlazoTranscurrido + 1) WHERE C.DiaCobro = DAY(CURDATE()) AND ((C.Estado = 'Renta' AND DATEDIFF(CURDATE(), CO.FechaCreacion) >= 30) OR C.Estado = 'Activo' OR C.Estado = 'Perpetuo');

        -- UPDATE CARGOFIJO AS C INNER JOIN CONTRATO AS CO ON C.IdContrato = CO.IdContrato INNER JOIN PROPIEDAD AS PR ON CO.IdPropiedad = PR.IdPropiedad SET C.PlazoTranscurrido = (C.PlazoTranscurrido + 1) WHERE C.DiaCobro = DAY(CURDATE()) AND CO.IdUnidad IS NULL AND (C.Estado = 'Perpetuo' OR C.Estado = 'Activo') AND ((C.Estado = 'Perpetuo' AND DATEDIFF(CURDATE(), CO.FechaCreacion) >= 30) OR C.Estado = 'Activo');

        UPDATE CARGOFIJO SET Estado = 'Completado' WHERE PlazoTranscurrido = Plazo;

    end;

-- Administrador/DETALLECONTRATO

DROP PROCEDURE IF EXISTS SP_GETCONTRATOINFO;
CREATE PROCEDURE SP_GETCONTRATOINFO(IN IDCONTRA INT)
BEGIN
    DECLARE TIPOVAR VARCHAR(30);

    SET TIPOVAR = (SELECT P.Tipo FROM CONTRATO AS C INNER JOIN PROPIEDAD P on C.IdPropiedad = P.IdPropiedad WHERE C.IdContrato = IDCONTRA);

    -- OBETNER INFORMACIÓN DEL CONTRATO
    IF TIPOVAR != 'Edificio' THEN
        SELECT C.IdContrato, 'Propiedad' AS Tipo, P.Nombre AS NombreInmueble, (SELECT FN_OBTENERDIRECCION(P.Direccion)) AS Direccion, C.Estado, DATE_FORMAT(C.FechaCreacion, '%d/%m/%Y') AS FechaCreacion, C.Plazo, CA.DiaCobro, CA.Monto AS MontoRenta, C.Deposito, (SELECT FN_GETNOMBREBYID(C.IdPersona)) AS Inquilino, PE.Telefono FROM CONTRATO AS C INNER JOIN PROPIEDAD AS P ON C.IdPropiedad = P.IdPropiedad INNER JOIN CARGOFIJO AS CA ON C.IdContrato = CA.IdContrato INNER JOIN PERSONA AS PE ON C.IdPersona = PE.IdPersona WHERE C.IdContrato = IDCONTRA AND CA.Estado = 'Renta' AND C.Estado = 'Activo';

    ELSE
        SELECT C.IdContrato, 'Unidad' AS Tipo, U.Nombre AS NombreInmueble, (SELECT FN_OBTENERDIRECCION(P.Direccion)) AS Direccion, C.Estado, DATE_FORMAT(C.FechaCreacion, '%d/%m/%Y') AS FechaCreacion, C.Plazo, CA.DiaCobro, CA.Monto AS MontoRenta, C.Deposito, (SELECT FN_GETNOMBREBYID(C.IdPersona)) AS Inquilino, PE.Telefono FROM CONTRATO AS C INNER JOIN UNIDAD U on C.IdUnidad = U.IdUnidad INNER JOIN PROPIEDAD P on U.Propiedad = P.IdPropiedad INNER JOIN CARGOFIJO AS CA ON C.IdContrato = CA.IdContrato INNER JOIN PERSONA AS PE ON C.IdPersona = PE.IdPersona WHERE C.IdContrato = IDCONTRA AND CA.Estado = 'Renta' AND C.Estado = 'Activo';
    end if;

    -- OBTENER INFORMACIÓN DE LOS CARGOS FIJOS
    SELECT C.IdCargoFijo, C.Descripcion, C.Monto, C.DiaCobro, C.Plazo, C.PlazoTranscurrido, C.Estado FROM CARGOFIJO AS C INNER JOIN CONTRATO AS CO ON C.IdContrato = CO.IdContrato WHERE C.Estado != 'Eliminado' AND CO.IdContrato = IDCONTRA;

    -- OBTENER INFORMACIÓN DE LOS CARGOS
    SELECT C.IdCargo, C.Descripcion, C.MontoTotal, DATE_FORMAT(C.FechaInicio, '%d/%m/%Y') AS FechaInicio, DATE_FORMAT(C.FechaVencimiento, '%d/%m/%Y') AS FechaVencimiento, C.Estado, C.SaldoPendiente, C.TipoCargo FROM CARGO AS C INNER JOIN CONTRATO AS CO ON C.IdContrato = CO.IdContrato WHERE CO.IdContrato = IDCONTRA AND C.Estado != 'Eliminado';

end;
call SP_GETCONTRATOINFO(1);
DROP PROCEDURE IF EXISTS SP_GETINQUILINOINFO;
CREATE PROCEDURE SP_GETINQUILINOINFO(IN IDCONTRATOIN INT)
    BEGIN
        SELECT P.Nombre, P.ApellidoPaterno, P.ApellidoMaterno, P.Telefono FROM CONTRATO AS C INNER JOIN PERSONA AS P ON C.IdPersona = P.IdPersona WHERE IdContrato = IDCONTRATOIN;
    end;

DROP PROCEDURE IF EXISTS SP_EDITINQUILINO;
CREATE PROCEDURE SP_EDITINQUILINO(IN IDCONTRATOIN INT, IN NOMBREIN VARCHAR(300), IN APELLIDOPAT VARCHAR(300), IN APELLIDOMAT VARCHAR(300), IN TELEFONOIN VARCHAR(300))
    BEGIN
        UPDATE PERSONA AS P INNER JOIN CONTRATO AS C ON P.IdPersona = C.IdPersona SET P.Nombre = NOMBREIN, P.ApellidoPaterno = APELLIDOPAT, P.ApellidoMaterno = APELLIDOMAT, P.Telefono = TELEFONOIN WHERE C.IdContrato = IDCONTRATOIN;
    end;

DROP PROCEDURE IF EXISTS SP_GETCARGOFIJOINFO;
CREATE PROCEDURE SP_GETCARGOFIJOINFO(IN IDCARGOIN INT)
    BEGIN
        SELECT C.Descripcion, C.Monto, C.DiaCobro, C.Plazo, C.Estado FROM CARGOFIJO AS C WHERE C.IdCargoFijo = IDCARGOIN;
    end;

DROP PROCEDURE IF EXISTS SP_EDITCARGOFIJO;
CREATE PROCEDURE SP_EDITCARGOFIJO(IN IDCARGOIN INT, IN DESCRIPCIONIN VARCHAR(255), IN MONTOIN DECIMAL(10,2), IN DIAIN INT, IN PLAZOIN INT, IN ESTADOIN VARCHAR(50))
    BEGIN
        DECLARE PLAZOVAR, PLAZOTRANSCURRIDOVAR INT;
        DECLARE ESTADOVAR VARCHAR(50);

        IF ESTADOIN != 'Renta' THEN

            SET ESTADOVAR = (SELECT Estado FROM CARGOFIJO WHERE IdCargoFijo = IDCARGOIN);

            SET PLAZOVAR = (SELECT C.Plazo FROM CARGOFIJO AS C WHERE C.IdCargoFijo = IDCARGOIN);

            IF PLAZOVAR = PLAZOIN THEN
                SET PLAZOTRANSCURRIDOVAR = (SELECT C.PlazoTranscurrido FROM CARGOFIJO AS C WHERE C.IdCargoFijo = IDCARGOIN);
            ELSE
                SET PLAZOTRANSCURRIDOVAR = 0;
            end if;

            IF ESTADOVAR = 'Perpetuo' AND PLAZOIN != -1 THEN
                SET ESTADOIN = 'Activo';
            end if;

            IF PLAZOIN = -1 AND (ESTADOIN != 'Pausado' AND ESTADOIN != 'Completado')  THEN
                SET ESTADOIN = 'Perpetuo';
                SET PLAZOTRANSCURRIDOVAR = 0;
            end if;

            IF ESTADOIN = 'Pausado' OR ESTADOIN = 'Completado' THEN
                UPDATE CARGOFIJO SET Descripcion = DESCRIPCIONIN, Monto = MONTOIN, DiaCobro = DIAIN, Estado = ESTADOIN WHERE IdCargoFijo = IDCARGOIN;
            ELSE
                UPDATE CARGOFIJO SET Descripcion = DESCRIPCIONIN, Monto = MONTOIN, DiaCobro = DIAIN, PlazoTranscurrido = PLAZOTRANSCURRIDOVAR, Plazo = PLAZOIN, Estado = ESTADOIN WHERE IdCargoFijo = IDCARGOIN;
            end if;

        ELSE

            UPDATE CARGOFIJO SET Descripcion = DESCRIPCIONIN, Monto = MONTOIN, DiaCobro = DIAIN WHERE IdCargoFijo = IDCARGOIN;

        end if;


    end;

DROP PROCEDURE IF EXISTS SP_DELETECARGOFIJO;
CREATE PROCEDURE SP_DELETECARGOFIJO(IN IDCARGOFIJOIN INT)
    BEGIN
        UPDATE CARGOFIJO SET Estado = 'Eliminado' WHERE IdCargoFijo = IDCARGOFIJOIN;
    end;

DROP PROCEDURE IF EXISTS SP_ADDCARGO;
CREATE PROCEDURE SP_ADDCARGO(IN IDCONTRATOIN INT, IN DESCRIPCIONIN VARCHAR(255), IN MONTOIN DECIMAL(10,2), IN TIPOIN VARCHAR(50), IN DIACOBROIN INT, IN PLAZOIN INT, IN FECHAINICIOIN VARCHAR(30), IN FECHAVENCIMIENTOIN VARCHAR(30))
    BEGIN

        DECLARE TIPOVAR VARCHAR(100);

        IF TIPOIN = 'Fijo' THEN

            IF PLAZOIN != -1 THEN
                SET TIPOVAR  = 'Activo';
            ELSE
                SET TIPOVAR = 'Perpetuo';
            end if;

            INSERT INTO CARGOFIJO (Descripcion, Monto, DiaCobro, IdContrato, Estado, Plazo) VALUES (DESCRIPCIONIN, MONTOIN, DIACOBROIN, IDCONTRATOIN, TIPOVAR, PLAZOIN);

        ELSE
            IF FECHAINICIOIN = '' THEN
                SET FECHAINICIOIN = CURDATE();
            end if;

            IF FECHAINICIOIN != CURDATE() THEN
                SET TIPOVAR = 'Programado';
            ELSE
                SET TIPOVAR = 'Pendiente';
            end if;

            INSERT INTO CARGO (IdContrato, TipoCargo, Descripcion, MontoTotal, FechaInicio, FechaVencimiento, Estado, SaldoPendiente) VALUES (IDCONTRATOIN, TIPOIN, DESCRIPCIONIN, MONTOIN, FECHAINICIOIN, FECHAVENCIMIENTOIN, TIPOVAR, MONTOIN);
        end if;
    end;

DROP PROCEDURE IF EXISTS SP_DELETECARGO;
CREATE PROCEDURE SP_DELETECARGO(IN IDCARGOIN INT)
    BEGIN
        UPDATE CARGO SET Estado = 'Eliminado' WHERE IdCargo = IDCARGOIN;
    end;

DROP PROCEDURE IF EXISTS SP_GETCARGOINFO;
CREATE PROCEDURE SP_GETCARGOINFO(IN CARGOIN INT)
    BEGIN
        SELECT C.TipoCargo, C.Descripcion, C.MontoTotal, DATE_FORMAT(C.FechaInicio, '%Y-%m-%d') AS FechaInicio, DATE_FORMAT(C.FechaVencimiento, '%Y-%m-%d') AS FechaVencimiento, C.Estado, C.SaldoPendiente FROM CARGO AS C WHERE C.IdCargo = CARGOIN;
    end;

DROP PROCEDURE IF EXISTS SP_UPDATECARGO;
CREATE PROCEDURE SP_UPDATECARGO(IN IDCARGOIN INT, IN DESCRIPCIONIN VARCHAR(255), IN ESTADOIN VARCHAR(30), IN FECHAINICIOIN VARCHAR(30), IN FECHAVENCIMIENTOIN VARCHAR(30), IN MONTOIN DECIMAL(10,2), IN SALDOIN DECIMAL(10,2), IN TIPOIN VARCHAR(50))
    BEGIN

        IF FECHAINICIOIN = CURDATE() THEN
            SET ESTADOIN = 'Pendiente';
        end if;

        IF ESTADOIN != 'Pagado' AND FECHAINICIOIN != CURDATE() AND TIPOIN != 'FIjo' THEN
            SET ESTADOIN = 'Programado';
        end if;

        IF MONTOIN != SALDOIN and ESTADOIN = 'Pendiente' THEN
                SET ESTADOIN = 'Parcial';
            end if;

        UPDATE CARGO SET TipoCargo = TIPOIN, Descripcion = DESCRIPCIONIN, MontoTotal = MONTOIN, FechaInicio = FECHAINICIOIN, FechaVencimiento = FECHAVENCIMIENTOIN, Estado = ESTADOIN, SaldoPendiente = SALDOIN WHERE IdCargo = IDCARGOIN;

    end;

DROP PROCEDURE IF EXISTS SP_FINALIZARCONTRATO;
CREATE PROCEDURE SP_FINALIZARCONTRATO(IN IDCONTRATOIN INT)
    BEGIN
        UPDATE CONTRATO SET Estado = 'Finalizado' WHERE IdContrato = IDCONTRATOIN;

        UPDATE CARGO AS C INNER JOIN CONTRATO AS CO ON C.IdContrato = CO.IdContrato SET C.Estado = 'Cancelado' WHERE CO.IdContrato = IDCONTRATOIN;

        UPDATE CARGOFIJO AS C INNER JOIN CONTRATO AS CO ON C.IdContrato = CO.IdContrato SET C.Estado = 'Cancelado' WHERE CO.IdContrato = IDCONTRATOIN;
    end;


-- Administrador/PAGOS

DROP FUNCTION IF EXISTS FN_OBTENERNOMBREINMUEBLE;
CREATE FUNCTION FN_OBTENERNOMBREINMUEBLE(IDPROP INT, IDUNI INT)
    RETURNS VARCHAR(100)
    DETERMINISTIC
    BEGIN
        DECLARE NOMBREVAR VARCHAR(100);
        IF IDUNI IS NULL THEN
            SET NOMBREVAR = (SELECT Nombre FROM PROPIEDAD WHERE IdPropiedad = IDPROP);
        ELSE
            SET NOMBREVAR = (SELECT CONCAT(P.Nombre, ' - ', U.Nombre) FROM UNIDAD AS U INNER JOIN PROPIEDAD P on U.Propiedad = P.IdPropiedad WHERE U.IdUnidad = IDUNI AND P.IdPropiedad = IDPROP);
        end if;

        RETURN NOMBREVAR;
    end;

DROP PROCEDURE IF EXISTS SP_GETCARGOSPAGO;
CREATE PROCEDURE SP_GETCARGOSPAGO()
    BEGIN
        SELECT C.IdCargo, CO.IdContrato, C.Descripcion, C.MontoTotal, C.SaldoPendiente, DATE_FORMAT(C.FechaInicio, '%d/%m/%Y') AS FechaInicio, DATE_FORMAT(C.FechaVencimiento, '%d/%m/%Y') AS FechaVencimiento, C.Estado, C.TipoCargo, (SELECT FN_GETNOMBREBYID(CO.IdPersona)) AS Inquilino, (SELECT FN_OBTENERNOMBREINMUEBLE(PR.IdPropiedad, U.IdUnidad)) AS Inmueble, P.Telefono, (SELECT FN_OBTENERDIRECCION(PR.Direccion)) AS DireccionInmueble FROM CARGO AS C INNER JOIN CONTRATO AS CO ON C.IdContrato = CO.IdContrato AND CO.Estado = 'Activo' INNER JOIN PROPIEDAD PR on CO.IdPropiedad = PR.IdPropiedad AND PR.Estatus = 'Activo' INNER JOIN PERSONA AS P ON CO.IdPersona = P.IdPersona LEFT JOIN UNIDAD AS U ON CO.IdUnidad = U.IdUnidad WHERE C.Estado = 'Pendiente' OR C.Estado = 'Parcial' OR C.Estado = 'Vencido';
    end;

DROP PROCEDURE IF EXISTS SP_REGISTRARABONO;
CREATE PROCEDURE SP_REGISTRARABONO(IN IDCARGOIN INT, IN MONTOIN DECIMAL(10,2), IN USUARIOIN INT)
    BEGIN
        DECLARE SALDOACTUAL DECIMAL(10,2);
        DECLARE NUEVOSALDO DECIMAL(10,2);
        DECLARE NUEVOESTADO VARCHAR(20);

        DECLARE EXIT HANDLER FOR SQLEXCEPTION
        BEGIN
            ROLLBACK;
            SELECT 0 AS RES, 'Error al registrar el abono' AS MSG;
        END;

            START TRANSACTION;

        SET SALDOACTUAL = (SELECT SaldoPendiente FROM CARGO WHERE IdCargo = IDCARGOIN);

        IF MONTOIN > SALDOACTUAL THEN
            ROLLBACK;
            SELECT 0 AS RES, 'El monto del abono no puede ser mayor al saldo pendiente' AS MSG;
        ELSE
            SET NUEVOSALDO = SALDOACTUAL - MONTOIN;

            IF NUEVOSALDO = 0 THEN
                SET NUEVOESTADO = 'Pagado';
            ELSE
                SET NUEVOESTADO = 'Parcial';
            END IF;

            INSERT INTO ABONO (IdCargo, Usuario, Monto) VALUES (IDCARGOIN, USUARIOIN, MONTOIN);

            UPDATE CARGO SET SaldoPendiente = NUEVOSALDO, Estado = NUEVOESTADO WHERE IdCargo = IDCARGOIN;
            COMMIT;

            SELECT 1 AS RES, 'Abono registrado correctamente' AS MSG;

        end if;

    end;

CALL SP_REGISTRARABONO(7,100,1001);
SELECT * FROM ABONO;

-- DATOS INICIALES
SELECT * FROM PROPIEDAD;
SELECT * FROM CONTRATO;
select * from ABONO;
select CURDATE();

UPDATE CARGO SET Estado = 'Pagado', SaldoPendiente = 0 WHERE IdCargo = 18;

INSERT CARGOFIJO (Descripcion, Monto, DiaCobro, IdContrato, Estado, Plazo) VALUES ('TEST123', 100, 9, 1, 'Activo', 3);

SELECT @@global.time_zone, @@session.time_zone;
SET time_zone = 'America/Mexico_City';
    SELECT curdate();
SELECT * FROM CARGO AS C WHERE C.FechaVencimiento > CURDATE();

SELECT DATE_ADD(DATE_ADD(DATE_FORMAT(CURDATE(), '%Y-%m-15'), INTERVAL 1 MONTH), INTERVAL 2 WEEK);

SELECT (DATE_ADD(DATE_FORMAT(CURDATE(), CONCAT(LPAD(15, 2, '0'), '/%m/%Y')), INTERVAL 1 MONTH));

SELECT DATE_FORMAT(DATE_ADD(DATE_FORMAT(CURDATE(), CONCAT('%Y-%m-', LPAD(15, 2, '0'))), INTERVAL 1 MONTH), '%d/%m/%Y');

INSERT INTO DIRECCION (IdCodigoPostal, IdColonia, Calle) SELECT IdCodigoPostal, 72856, 'Victoria 54' FROM CODIGOPOSTAL WHERE CodigoPostal = '38800' LIMIT 1;
INSERT INTO DIRECCION (IdCodigoPostal, IdColonia, Calle) SELECT IdCodigoPostal, 119795, 'Allende 32' FROM CODIGOPOSTAL WHERE CodigoPostal = '58000' LIMIT 1;

INSERT INTO ROL (Rol) VALUE ('Vendedor');
INSERT INTO ROL (Rol) VALUE ('Cajero');
INSERT INTO ROL (Rol) VALUE ('Administrador');
select * from UNIDAD;
INSERT INTO ESTATUS (ESTATUS) VALUES ('Activo');
INSERT INTO ESTATUS (ESTATUS) VALUES ('Despedido');
INSERT INTO ESTATUS (ESTATUS) VALUES ('Suspendido');
INSERT INTO ESTATUS (ESTATUS) VALUES ('Eliminado');

INSERT INTO PERSONA (Nombre, ApellidoPaterno, ApellidoMaterno, Telefono) VALUES ('Pedro', 'Villa', 'Almanza', '4457963475');
INSERT INTO EMPLEADO (IdPersona, IdRol, IdEstatus) VALUES ((SELECT LAST_INSERT_ID()), 3, 1);
INSERT INTO USUARIO (Contraseña, IdEmpleado) VALUES ('$2b$10$VuHF8B70UNBN.MmD6vS20eigaxYkUjkCi.mcxtRVJqQwpnDkua2jq', 1);

CALL SP_REGISTRAREMPLEADO('123456','Francisco', 'Leal', 'Medina', '4459721648', 3, 1, 1001);

CALL SP_ADDPROPIEDAD('Departamentos Pipila', 'Edificio', 38800, 72856, 'Pipila 706');
CALL SP_ADDUNIDAD('Departamento 1', 1);
CALL SP_ADDUNIDAD('Departamento 2', 1);
CALL SP_ADDUNIDAD('Departamento 3', 1);
CALL SP_ADDUNIDAD('Departamento 4', 1);
CALL SP_ADDUNIDAD('Departamento 5', 1);
CALL SP_ADDUNIDAD('Departamento 6', 1);
CALL SP_ADDUNIDAD('Departamento 7', 1);
CALL SP_ADDUNIDAD('Departamento 8', 1);

CALL SP_ADDPROPIEDAD('Casa Puebla', 'Casa', 38800, 72856, 'Puebla 201');


SELECT * FROM DIRECCION;

SELECT * FROM USUARIO;

SELECT * FROM EMPLEADO;

SELECT * FROM ROL;

UPDATE EMPLEADO SET IdEstatus = 1 WHERE IdEmpleado = 1;

UPDATE EMPLEADO SET IdRol = 3 WHERE IdEmpleado = 2;

SELECT * FROM USUARIO;

UPDATE USUARIO SET Contraseña = '$2b$10$VuHF8B70UNBN.MmD6vS20eigaxYkUjkCi.mcxtRVJqQwpnDkua2jq' WHERE IdUsuario = 1001;

SELECT * FROM PERSONA;

CALL SP_UPDATEEMPLEADO(2,'TEST','TEST2','TEST3','12121',1,1);


CALL LOGIN(1001, '123456');

SELECT * FROM USUARIO;


SELECT ObtenerDireccion(38940);

SELECT CONCAT(E.Estado, ' ', M.Municipio, ' ', C2.Colonia, ' ', C.CodigoPostal) AS DIRECCION FROM ESTADO AS E INNER JOIN MUNICIPIO AS M ON E.IdEstado = M.IdEstado INNER JOIN CODIGOPOSTAL AS C ON M.IdMunicipio = C.IdMunicipio INNER JOIN COLONIA C2 on C.IdCodigoPostal = C2.IdCodigoPostal WHERE C.CodigoPostal = 29000;

SELECT CONCAT(E.IdEstado, ' ', M.IdMunicipio, ' ', C2.Colonia, ' ', C.CodigoPostal) AS DIRECCION FROM ESTADO AS E INNER JOIN MUNICIPIO AS M ON E.IdEstado = M.IdEstado INNER JOIN CODIGOPOSTAL AS C ON M.IdMunicipio = C.IdMunicipio INNER JOIN COLONIA C2 on C.IdCodigoPostal = C2.IdCodigoPostal WHERE C.CodigoPostal = 29000;

CALL SP_OBTENERCOLONIAS('58000');

select * from ESTATUS;